version: '3.7'

services:
   prometheus:
     image: prom/prometheus:latest
     volumes:
       - ./prometheus.yaml:/etc/prometheus/prometheus.yaml
       - prometheus_data:/prometheus
       - ./alert_rules.yaml:/etc/prometheus/alert_rules.yaml
     command:
       - '--config.file=/etc/prometheus/prometheus.yaml'
       - '--web.external-url=http://10.88.72.245:9090/'

     ports:
       - 9090:9090

   alertmanager:
     image: prom/alertmanager
     ports:
       - 9093:9093
     volumes:
       - ./alertmanager.yaml/:/etc/alertmanager/alertmanager.yaml
     restart: always
     command:
       - '--config.file=/etc/alertmanager/alertmanager.yaml'
       - '--storage.path=/alertmanager'
       - '--web.external-url=http://10.88.72.245:9093/'

volumes:
     prometheus_data:
